#!/bin/bash

# Make sure the following script is found earlier in
# the PATH than the original one and it will be used
# Set it in /usr/local/bin/ for example
# Alternatively you can specify the bin path
# in the [nvidia-container-cli] section in
# /etc/nvidia-container-runtime/config.toml

set -ex -o pipefail -u

CONTAINER_CLI_PATH=${CONTAINER_CLI_PATH:-/usr/bin/nvidia-container-cli}

exit_trap () {
  local lc="$BASH_COMMAND" rc=$?
  echo "Nvidia container cli wrapper failed. [$lc] exited with code [$rc]" | tee >&2
}

trap exit_trap EXIT
{
    echo "Calling nvidia container cli wrapper"
    echo "$@"

    echo Identifying target pid
    p=$(echo $(echo "$@" | grep -oP '\s+(-p|--pid)(=|\s+)\K(\d+)(\s|$)'))

    echo Container pid $p

    cgroupPath=/sys/fs/cgroup/$(cat /proc/$p/cgroup | grep -oP '^\d+::/\K.*')

    echo Cgroup path $cgroupPath

    $CONTAINER_CLI_PATH $@

    gpuacl $cgroupPath
} > /tmp/log1.log 2>&1